# Generated by Django 4.2.6 on 2023-10-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_m',
            fields=[
                ('eid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('age', models.PositiveSmallIntegerField(default=18, null=True)),
                ('address', models.TextField()),
                ('doj', models.DateField()),
                ('dom', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
