# Generated by Django 4.2.6 on 2023-10-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_numbermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbermodel',
            name='num2',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbermodel',
            name='num3',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
