# Generated by Django 4.2.6 on 2023-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_filemodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='boolmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool1', models.BooleanField()),
                ('bool2', models.BinaryField()),
            ],
        ),
    ]
